name:                CS316Coursework2021
version:             0.1.0.0
github:              "githubuser/CS316Coursework2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns

executables:
  csv-query:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS316Coursework2021

tests:
  csv-query-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS316Coursework2021
